### PR TITLE
Grails4

### PR DESCRIPTION
**Pull request by billgonemad**
I have a branch that seems to be working with Grails 4.  Note that I am unsure if these changes work in grails 3 but I am using them in my local Grails 4.0.3 project that uses this plugin.  One change I was unsure of was the fact that I needed to comment out the coAuthor property on the Book domain class to get any test cases to run.  All existing test cases are passing with this change.

### CODE REVIEW

**Comment by rafapaisley** [comment]
We are eager waiting for this merge !!!

**Comment by ctoestreich** [comment]
I am not sure if the build deploy script still work due to being idle for so long....

**Comment by rafapaisley** [comment]
Looks like the JDK installation is failing...
You should add:

dist: trusty

To your .travis.yml file :)

**Comment by ktsobal** [comment]
@ctoestreich Thank you for your solution. **It works!** The only problem I found, was in the Methode currentCriteria in FilterPaneTagLib. There's no ".referencedDomainClass" and ".referencedPropertyType" in "domainProp". I fixed it with ".owner" and ".type".
I hope this will help you. I'm excited about the next merge.

**Pull request merged**
